---
- name: Conditional vars inclusion based on host_vars 
  hosts: all
  gather_facts: no
  
  tasks:

  
    - name: Display values
      debug:
        msg: "{{ value }}" 
        
    - name: Display values
      debug:
        msg: "{{ value | map(attribute='value')| list }}" 
