---
- name: Conditional vars inclusion based on host_vars 
  hosts: all
  gather_facts: no
  
  tasks:

  
    - name: Display values
      debug:
        msg: "{{ value }}" 
        
    - name: Extract Custom Prop Value
      set_fact:
        vm_props: "{{ value | map(attribute='value')| list }}" 
        
    - name: Include for first group
      include_vars:
        file: first.yml
      when: '"dcl-1" in vm_props'
      
    - name: Include for second group
      include_vars:
        file: second.yml
      when: '"dcl-2" in vm_props'

    - name: Display imported value
        msg: "{{ my_imported_value }}"

