---
- name: Conditional vars inclusion based on host_vars 
  hosts: all
  gather_facts: no
  
  tasks:

  
    - name: Display values
      debug:
        msg: "{{ value }}" 
        
    - name: Display values
      debug:
        msg: "{{ value | map(attribute='value')| list }}" 
        
    - name: Include for first group
      include_vars:
        name: first.yml
      when: "dcl-1" in value | map(attribute="value") | list
      
    - name: Include for second group
      include_vars:
        name: second.yml
      when: '"dcl-2" in value | map(attribute="value") | list

